### ISSUE TITLE
When no URL is provided, preventDefault should be used.

### ISSUE THREAD

**Issue by sessa** [Julienh/Sharrre#20]
```facebook: { 
url: '',  //if you need to personalize url button
}```

When URL is empty, a hash (#) is added to the href attribute of the a tag.  Instead it should not add a hash and just e.preventDefault on the "click" event.

```
    $(this.element).click(function(e){
      e.preventDefault();
      self.options.click(self, self.options);
      return false;
    });
```

**Comment by smeeckaert** [comment]
It's been corrected.

**Comment by Althemenes** [comment]
Hey! 

Just wanted to say  hello  and  wish you a good day! By the way, have you seen that  <http://wanted.notebooknine.com/e6frewy>


Best Wishes, tadakute
