### ISSUE TITLE
Twitter shutting off share counts soon (via JSON) 

### ISSUE THREAD

**Issue by pagelab** [Julienh/Sharrre#258]
https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

This will happen in November 20, and will affect pretty much [every share button](http://warfareplugins.com/is-twitter-seriously-removing-share-counts-why-would-they-do-this/) out there. 

The much more complex [REST API](https://dev.twitter.com/rest/public) will be the only choice to grab share counts now.

**Comment by sphism** [comment]
Is there any plan to support twitter rest api tweet counts in sharrre? We're using it on a project, and really like it, I'm just looking into it today to figure out what we're gong to do. I'm not sure there is a direct equivalent of total share count in the REST API, but maybe there is.

I'm also wondering if sharrre is going to fail gracefully once the existing api endpoint vanishes, will it just be a 0 tweet count or a fatal error?

**Comment by ISB7** [comment]
Same problem. I use REST API Twitter. Is there a way to solve the problem (20th november) ? Support ?

**Comment by djiesamsoe** [comment]
I wait for the development of the case and the new update

**Comment by briankelleher** [comment]
Any ideas on how to fix this?  This change broke all my share buttons, I commented out the twitter section from the urlJson section where they defined the twitter count url, but the buttons still do not render.  No javascript errors either.  If I try and set `enableCounter` to false, it causes my buttons not to render as well.

**Comment by pagelab** [comment]
http://opensharecount.com/

**Comment by sphism** [comment]
Ok so our sharrre count no longer loads, but it fails gracefully. Then the twitter button doesn't do anything when you click it... We tried the official alternative and it doesn't work at all. Searching for the url's of our pages produced no results. Will try opensharecount, thanks for that @pagelab

**Comment by sphism** [comment]
Right well I'm using http://opensharecount.com/ now and the combined share counts are getting calculated correctly again, and my twitter button opens the popup again since there's no longer a javascript error in there preventing it.

I'm not seeing any actual count results for twitter, all the ones i've tested are 0... but I'm guessing either opensharecount takes a while to update... or they are using the twitter rest search api which I didn't manage to return results for our url's either.

**Comment by sphism** [comment]
Raised a PR for using opensharecount api instead of old twitter api:

https://github.com/Julienh/Sharrre/pull/260

**Comment by smeeckaert** [comment]
The problem should be resolved now.
