### ISSUE TITLE
The widget has stopped working

### ISSUE THREAD

**Issue by srcreative-steveporter** [Julienh/Sharrre#262]
Hi, I have the plugin installed on a few sites and it's stopped working on all sites. During investigation I looked at the demos on http://sharrre.com/ and relised that theydidnt work either. Checked on FireFox 42.0 (windows 10)

**Comment by srcreative-steveporter** [comment]
Just noticed the thread - Twitter shutting off share counts soon (via JSON) - could this be related?

**Comment by Mike-Hermans** [comment]
I guess so, all websites that use the twitter button get a 404 error on the json url. Can confirm the problem. You can remove line 108: `twitter: 'https://cdn.api.twitter.com/1/urls/count.json?url={url}&callback=?',` or just comment it out. This seemed to resolve the 404 error, but my styling is still messed up (either the button doesn't show at all, or it's in the wrong location).

**Comment by smeeckaert** [comment]
If you want the plugin to work again, you can either disable twitter count, or update it and create an account on [OpenShareCount](http://opensharecount.com/) to have the twitter count.
