### ISSUE TITLE
Twitter doesn't work anymore

### ISSUE THREAD

**Issue by codeyourweb** [Julienh/Sharrre#264]
I'm using sharrre on my website for a long time and i just realize that twitter sharing button is no more active. This problem is also occuring on official sharrre website (http://sharrre.com/example1.html). Is there a way to fix this problem?

**Comment by Mike-Hermans** [comment]
Twitter removed the link to get the share count. This seems to break a lot of Twitter buttons. See #258 for something that may fix this.

**Comment by chalavacs** [comment]
More info on the removal of Twitter's Tweet count endpoint:

- http://stackoverflow.com/a/33893042
- https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

**Comment by smeeckaert** [comment]
Now you can create an account on [OpenShareCount](http://opensharecount.com/) if you want to use the feature.
