### ISSUE TITLE
how about a recent .mim version  !!

### ISSUE THREAD

**Issue by pbearne** [Julienh/Sharrre#268]
I was pulling this ot fixed the twitter count problem but quickly found out the ,min is 2 years old

So had to make mine own :-)

Paul

**Comment by smeeckaert** [comment]
Now the [2.0.0 branch](https://github.com/Julienh/Sharrre/tree/2.0.0) has an up-to-date version, but be careful this version is still unofficial.

**Comment by Althemenes** [comment]
Hey, 
Have  you heard the  latest  news? You're  gonna love this,  check it out  here <http://hashiduphe.swofoa.org/e6rrmd>
Cheers, tadakute
