### ISSUE TITLE
Twitter API Stopper working, status shows 410 gone

### ISSUE THREAD

**Issue by noesisconsultancy** [Julienh/Sharrre#271]
Twitter API Stopper working, status shows 410 gone
Its reported from last 5-10 days from one of our client

**Comment by IanCaunce** [comment]
Seems it stopped working Nov 20th. [Here] (https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform) is an official response regarding why the API was shut down.

**Comment by smeeckaert** [comment]
The twitter API has changed and now even with newer APIs you can't get the tweet count, and Twitter most likely won't change that. Right now you can use http://opensharecount.com/ that is configured in the latests versions. You need to register on opensharecount though.

**Comment by Althemenes** [comment]
Hi, That stuff is just gorgeous, you  have to read about it  more at <http://choice.pinkypc.us/e6yprho>

tadakute
