### ISSUE TITLE
Wordpress Setup

### ISSUE THREAD

**Issue by whizkydee** [Julienh/Sharrre#283]
The wordpress configuration for this plugin is irrelevantly difficult. Please consider creating a wordpress plugin. Thanks.

**Comment by smeeckaert** [comment]
Sharrre is not meant to support any CMS. You can check with https://github.com/paulund/sharrre-wordpress-plugin or https://github.com/DerekMarcinyshyn/wp-sharrre if you want a wordpress plugin.
