### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by extend1994** [Julienh/Sharrre#302]
Hi @Julienh 
I am a member from CDNJS and recently in charge of adding your lib, I need to check which license(s) is(are) used, only MIT or both MIT and GPLv2. Because https://github.com/Julienh/Sharrre#license and https://github.com/Julienh/Sharrre/blob/master/LICENSE only shows MIT but https://github.com/Julienh/Sharrre/blob/master/dist/jquery.sharrre.min.js#L5 shows both.
Thank you :)
BTW, You can see the process in https://github.com/cdnjs/cdnjs/pull/11619.

**Comment by Julienh** [comment]
Hi,
MIT Licence, 
thank you :)

**Comment by extend1994** [comment]
Thank you so much for quick reply 😄
