### ISSUE TITLE
Set counters to 0

### ISSUE THREAD

**Issue by EgonS** [Julienh/Sharrre#38]
Hi,

Perhaps a dumb question, but I can't seem to find the answer.

I added the Twitter, Facebook and the Google + buttons to my site mockup. But the counts on the button aren't 0. How do I "reset" the counters, so they start at zero?

Thank you!

**Comment by smeeckaert** [comment]
You can't reset the counters, they count the number of time the page where it is displayed has been shared on various platforms.
