### ISSUE TITLE
Facebook counter overlaps tweet button

### ISSUE THREAD

**Issue by RobertBouten** [Julienh/Sharrre#39]
I have recently used example 5 and set the buttons to be horizontal. But then the counter for the like button overlaps with the tweetbutton. Can this be avoided?

Furthermore somehow these 3 characters (â€‹) are generated in the script but they are now where to be found in the original script so I guess they are generated somewhere.....

**Comment by smeeckaert** [comment]
This problem doesn't seem to occur anymore.
