### ISSUE TITLE
Setting urlCurl to empty string results in 0 counts

### ISSUE THREAD

**Issue by Sire** [Julienh/Sharrre#62]
Tested in 1.3.2 (and latest dev version)
Setting urlCurl to '' always returns 0 on all pages. But no js error.
When removing or setting to a proper URL, everything works.

**Comment by smeeckaert** [comment]
It's kinda normal, urlCurl is defined by default to "sharrre.php", it is used to fetch some count APIs (mainly google+ and stumbleupon count). But it shouldn't affect other social medias.

**Comment by Althemenes** [comment]
Greetings, 

There is  some information  I found  recentle, I  thought you might like it, please read it here <http://delight.brokennevers.com/e6frj>

Later, tadakute
