### ISSUE TITLE
Images and LinkedIn Sharing

### ISSUE THREAD

**Issue by yaycmyk** [Julienh/Sharrre#67]
Hi Julien,

For some reason, image thumbnails are no longer being processed for LinkedIn share on my site. I have the proper og:image meta tags in the header and everything - any idea?

You can see an example here: http://www.brafton.com/news/watch-out-facebook-google-acquires-social-marketing-contest-tool-wildfire

Thanks for your time!

**Comment by smeeckaert** [comment]
Works fine from where i stand.
