### ISSUE TITLE
Main counter not counting or updating

### ISSUE THREAD

**Issue by tombosschaert** [Julienh/Sharrre#73]
On our site we've integrated Sharrre, which is really awesome, thanks for all the work!

We have a small problem we can't figure out: the 'total count' is not accurate, nor is it updating. This means the total count for some pages is at 0, while it has been shared on various things. On others, it sits at some number which is not the total of the amount of shares.

Look here: 
http://www.except.nl (total count not the actual total)
and here for 0 total, while it has been shared:
http://except.nl/en/#.en.news.207-wormfood-september-2-2012

Any idea where we should start looking? Thanks!

**Comment by smeeckaert** [comment]
It seems to work fine, now.
