### ISSUE TITLE
sharrre.php using wrong url

### ISSUE THREAD

**Issue by LimeBlast** [Julienh/Sharrre#75]
Hi, I've just launched a new e-commerce site, on which I've used the sharrre plugin, [as you can see here](http://www.charliemcleod.co.uk/product/chilled-charcoal-zippy/).

Now I'm not sure if I've done something wrong, but right now, the page linked to above should show 2 likes (as I've both tweeted it and added it to pinterest), but is currently only showing 1.

I think the issue related to the sharrre.php file, specifically the attributes being passed to it by the plugin, i.e. Firebug tells me that it's using:

http://www.charliemcleod.co.uk/sharrre.php?url=http%3A%2F%2Fwww.charliemcleod.co.uk%2Fproduct%2Fchilled-charcoal-zippy&type=pinterest

Which is returning a count of 0, but as soon as I add a final slash to the url, i.e.:

http://www.charliemcleod.co.uk/sharrre.php?url=http%3A%2F%2Fwww.charliemcleod.co.uk%2Fproduct%2Fchilled-charcoal-zippy/&type=pinterest

It then correctly shows a count of 1.

Seeing as the second URL (with the ending slash) is the correct URL, do you know why this isn't the value being passed to it by the plugin? (PS, as you can see, I'm also using GooglePlus, while I've not fully tested this, I can see that this is also using the wrong URL).

The jQuery code I'm using to call the widget is below:

	// product page sharrre links
	jQuery('#shareme').sharrre({
		share: {
			twitter: true,
			facebook: true,
			googlePlus: true,
			pinterest: true
		},
		template: '<div class="box"><div class="left">Share</div><div class="middle"><a href="#" class="facebook" title="Facebook">f</a><a href="#" class="twitter" title="Twitter">t</a><a href="#" class="googleplus" title="Google Plus">+1</a><a href="#" class="pinterest" title="Pinterest">p</a></div><div class="right">{total}</div></div>',
		enableHover: false,
		enableTracking: true,
		urlCurl: '/sharrre.php',
		render: function(api, options){
			jQuery(api.element).on('click', '.twitter', function() {
				api.openPopup('twitter');
			});
			jQuery(api.element).on('click', '.facebook', function() {
				api.openPopup('facebook');
			});
			jQuery(api.element).on('click', '.googleplus', function() {
				api.openPopup('googlePlus');
			});
			jQuery(api.element).on('click', '.pinterest', function() {
				api.openPopup('pinterest');
			});
		}
	});

Thank you :)

**Comment by smeeckaert** [comment]
You can change the url given to the API with the ```url``` parameter when instanciating Sharrre. By default it equals ```document.location.href```
